SET NOCOUNT ON
BEGIN TRY
 EXEC('TRUNCATE TABLE ' + @NOMETB)
END TRY
BEGIN CATCH
    SET ROWCOUNT 2000
    EXEC ('WHILE ((SELECT COUNT(1) FROM ' + @NOMETB + ' (NOLOCK)) > 0) DELETE FROM ' + @NOMETB)
    SET ROWCOUNT 0
END CATCH
SET NOCOUNT OFF
