SET NOCOUNT ON
BEGIN TRY
 EXEC('TRUNCATE TABLE ' + @NOMETB)
END TRY
BEGIN CATCH
    SET ROWCOUNT 2000
    EXEC ('WHILE ((SELECT COUNT(1) FROM ' + @NOMETB + ' (NOLOCK)) > 0) DELETE FROM ' + @NOMETB)
    SET ROWCOUNT 0
END CATCH
--EXEC sp_fkeys @NOMETB
----SE TABELA CONTEM FK ENT?O DEVE APAGAR COM DELETE
--IF (@@ROWCOUNT > 0)
--BEGIN
--    SET ROWCOUNT 2000
--    EXEC ('WHILE ((SELECT COUNT(1) FROM ' + @NOMETB + ' (NOLOCK)) > 0) DELETE FROM ' + @NOMETB)
--    SET ROWCOUNT 0
--END ELSE
--BEGIN
--    EXEC('TRUNCATE TABLE ' + @NOMETB)  
--END
SET NOCOUNT OFF

--DECLARE @COMANDO VARCHAR(200) = NULL
--SELECT @COMANDO = 'WHILE ((SELECT COUNT(1) FROM [' +  O.NAME + '] (NOLOCK)) > 0) DELETE FROM [' +  O.NAME + '];'
--FROM
--    SYS.OBJECTS O
--    INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS  C ON C.TABLE_NAME = O.NAME
--WHERE
--    C.CONSTRAINT_TYPE='FOREIGN KEY'
--    AND O.TYPE = 'U' AND O.IS_MS_SHIPPED = 0
--    AND O.NAME = @NOMETB
--GROUP BY O.NAME
--IF (@COMANDO IS NULL)
--    EXEC('TRUNCATE TABLE [' + @NOMETB + '];')
--ELSE
--BEGIN
--    SET ROWCOUNT 1500
--    EXEC(@COMANDO)
--    SET ROWCOUNT 0
--END

