SELECT
    LOWER(S.NAME) + '.' + UPPER(O.NAME) AS NM_TABLE, ISNULL(MAX(C.NAME),'') AS NM_COLUNA
FROM
    SYS.OBJECTS             O
 INNER JOIN SYS.SCHEMAS S ON O.schema_id = S.SCHEMA_ID
    LEFT JOIN SYS.COLUMNS   C ON C.OBJECT_ID = O.OBJECT_ID AND C.IS_IDENTITY = 1
WHERE
    O.IS_MS_SHIPPED = 0 AND O.TYPE = 'U' AND O.NAME NOT LIKE 'SYS%'
GROUP BY S.NAME, O.NAME
ORDER BY S.NAME, O.NAME

